baseURL: https://pion2023.nsaweb.nl
title: PION 2023
params:
  description: PION is an annual interuniversity physics olympiad for bachelor and master students from all over the Netherlands. Every year one of the universities in the Netherlands organizes Project Interuniversitaire Olympiade Natuurkunde (PION) and this year the honour is awarded to the NSA. PION is a physics olympiad for bachelor and master students from all over the Netherlands and is well supported by names like Robbert Dijkgraaf and Gerard 't Hooft.
  images: 
  - img/pion-pi.jpg
  - favicon.png
  - img/chess-pawn-solid-accent.svg
  title: PION 2023


disableKinds: ['taxonomy', 'term', 'tags', 'categories']

markup:
  defaultMarkdownHandler: goldmark
  asciidocExt:
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false
    attributes: {}
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
      attribute:
        block: true
        title: true
    renderer:
      hardWraps: true
      unsafe: true
      xhtml: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    hl_inline: false
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
